name: airport-service
replicaCount: 1

image:
  repository: malikslashtec/airport-service
  pullPolicy: Always
  tag: "1.0.1-1-abc123"  # This will be updated by Jenkins CI

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
  type: NodePort
  port: 8000
  targetPort: 8080

resources: 
  requests:
    cpu: 100m
    memory: 200m
container:
        port: 8080
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
namespace: "drone"

##for liveness and readiness  
path: "/health/live"
port: 8080