apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-airport-services
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: preprod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-unified
    repoURL: https://github.com/malikalaja/slashTEC.git
    targetRevision: main
    helm:
      valueFiles:
        - values-preprod.yaml
      parameters:
        - name: image.tag
          value: "1.0.1-1-${BUILD_NUMBER}"