apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-airport-services
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: preprod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /helm-unified
    repoURL: https://github.com/malikalaja/slashTEC.git
    targetRevision: v1.0.0